---
title: "Brackets on axes"
author: "Eric Scott"
date: "5/30/2019"
output: html_document
---

```{r}
library(ggplot2)
library(grid)
library(pBrackets) 
x <- c(runif(10),runif(10)+2)
y <- c(runif(10),runif(10)+2)
the_plot <- qplot(x=x,y=y) +
  scale_x_continuous("",breaks=c(.5,2.5),labels=c("Low types","High types") ) +
  theme(axis.ticks = element_blank(),
        axis.ticks.length = unit(.85, "cm"))


#Run grid.locator a few times to get coordinates for the outer
#most points of the bracket, making sure the 
#bottom_y coordinate is just at the bottom of the gray area.
# to exit grid.locator hit esc; after setting coordinates
# in grid.bracket comment out grid.locator() line
the_plot
grid.locator(unit="native") 
bottom_y <- 375
grid.brackets(220, bottom_y,   80, bottom_y, lwd=2, col="red")
grid.brackets(600, bottom_y,  440, bottom_y, lwd=2, col="red")
```

```{r}
bracketsGrob <- function(...){
l <- list(...)
e <- new.env()
e$l <- l
  grid:::recordGrob(  {
    do.call(grid.brackets, l)
  }, e)
}

b1 <- bracketsGrob(0.33, 0.0, 0, 0.0, h=0.05, lwd=2, col="red")
b2 <- bracketsGrob(1, 0.05, 0.66, 0.05, h=0.05,  lwd=2, col="red")

p <- the_plot + 
  annotation_custom(b1)+ 
  annotation_custom(b2) +
  scale_y_continuous(expand=c(0.11,0)) +
  coord_cartesian(clip = "off")
p

```


Now try with a heatmap

```{r}
library(tidyverse)
library(pBrackets)

bracketsGrob <- function(...){
l <- list(...)
e <- new.env()
e$l <- l
  grid:::recordGrob(  {
    do.call(grid.brackets, l)
  }, e)
}
mine.data <- read.csv(file = "https://tinyurl.com/mine-data-csv")

mine.long <- gather(data = mine.data, key = Class, value = Abundance, -c(1:3))
mine.heatmap <-
  ggplot(mine.long, aes(x = Sample.name,
                        y = Class,
                        fill = Abundance)) +
  geom_tile() +
  xlab(label = "Sample")

b1 <- bracketsGrob(3/8, 0, 0.01, 0, h=0.05)
b2 <- bracketsGrob(0.99, 0, 3/8, 0, h=0.05)

mine.heatmap +  
  coord_cartesian(ylim = c(1,10),clip = "off") +
  theme(axis.text.x =  element_blank(),
        axis.title.x = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = unit(c(1,1,3,1), "lines")) +
  annotation_custom(b1) + 
  annotation_custom(b2) +
  geom_text(data = tibble(x = c(2,6),
                          y = c(-0.5, -0.5),
                          label = c("A", "B")),
            aes(x, y, label=label),
            inherit.aes = FALSE)
```

