---
title: "R Notebook"
output: html_notebook
---

Test PCA-regression (linear model) vs. PCA-DA (linear discriminant analysis) vs. PCA-LR (logisitc regression)
```{r}
library(MASS)
library(here)
source(here("R", "pcr.R"))
```

`pcreg` coerces to numeric and does a linear regression

```{r}
pca_RMSEP_lr <- function(split, X_vars, Y_var) {
  #do pca on analysis(data)
  
  X <- enquo(X_vars)
  Y <- enquo(Y_var)
  # Do PCA on X
  pca <- opls(select(analysis(split), !!X), plotL = FALSE, printL = FALSE)
  
  # Get scores and bind with Y
  scores <-
    get_scores(pca) %>% 
    add_column(!!Y := analysis(split)[[quo_name(Y)]])
  
  #predict pc axis scores on assessment data
  scores.pred <- mypredict(pca, assessment(split) %>% select(!!X))
  
  # Make formula
  npcs <- pca@summaryDF$pre
  pcs <- glue("p{1:npcs}")
  mod_form <- as.formula(glue("{quo_name(Y)} ~ {glue_collapse(pcs, sep = '+')}"))
  
  #do glm on analysis data
  m <- glm(mod_form, family = "binomial", data = scores)
  
  #use glm to predict `group` for newdata
  scores.pred %>%
    mutate(group.pred = predict(m, newdata = scores.pred, type = "response")) %>%
    add_column(group.actual = assessment(split)[[quo_name(Y)]]) %>%
    mutate(sq_err = (group.actual - group.pred)^2) %>%
    summarize(RMSEP = sqrt(mean(sq_err))) %>%
    as.numeric()
}

pca_lr <- function(data, X_vars, Y_var, CV = 7){
  X <- enquo(X_vars)
  Y <- enquo(Y_var)
  
  #check if Y_var is factor or numeric
  if(is.character(data[[quo_name(Y)]])){
    data <-
      data %>% 
      mutate(!!Y := as.factor(!!Y)) %>% 
      mutate(!!Y := as.numeric(!!Y)-1)
  } 
  
  if(is.factor(data[[quo_name(Y)]])){
    data <-
      data %>%
      mutate(!!Y := as.numeric(!!Y)-1)
  }
  if(!is.numeric(data[[quo_name(Y)]])){
    stop("grouping variable must be character, factor, or numeric")
  }

  # Do PCA on X
  pca <- opls(select(data, !!X), plotL = FALSE, printL = FALSE)
  
  # Get scores and bind with Y
  scores <- get_scores(pca) %>% 
    add_column(!!Y := data[[quo_name(Y)]])
  
  # Make formula
  npcs <- pca@summaryDF$pre
  pcs <- glue("p{1:npcs}")
  mod_form <- as.formula(glue::glue("{quo_name(Y)} ~ {glue_collapse(pcs, sep = '+')}"))
  
  # Do regression
  m <- glm(mod_form, family = "binomial", data = scores)
  
  # Do CV
  df.cv <- rsample::vfold_cv(data, CV)
  RMSEP <- df.cv %>%
    mutate(RMSEP = map_dbl(.$splits, ~pca_RMSEP_lr(., !!X, !!Y))) %>% 
    summarize(RMSEP = mean(RMSEP)) %>%
    as.numeric()
  
  return(list(pca = pca, lm = m, RMSEP = RMSEP))
}

```


`pca_lr` does pca then logistic regression on retained pcs


```{r}
split <- df.cv$splits[[1]]

pca_RMSEP_da <- function(split, X_vars, Y_var) {
  #do pca on analysis(data)
  
  X <- enquo(X_vars)
  Y <- enquo(Y_var)
  # Do PCA on X
  pca <- opls(select(analysis(split), !!X), plotL = FALSE, printL = FALSE)
  
  # Get scores and bind with Y
  scores <-
    get_scores(pca) %>% 
    add_column(!!Y := analysis(split)[[quo_name(Y)]])
  
  #predict pc axis scores on assessment data
  scores.pred <- mypredict(pca, assessment(split) %>% select(!!X))
  
  # Make formula
  npcs <- pca@summaryDF$pre
  pcs <- glue("p{1:npcs}")
  mod_form <- as.formula(glue("{quo_name(Y)} ~ {glue_collapse(pcs, sep = '+')}"))
  
  #do glm on analysis data
  m <- lda(mod_form, data = scores)
  # m<-lda(group~p1+p2, data = scores)
  
  #use glm to predict `group` for newdata
  scores.pred %>%
    mutate(group.pred = predict(m, newdata = scores.pred, type = "response")$class) %>%
    add_column(group.actual = assessment(split)[[quo_name(Y)]] %>% as.factor()) %>%
    mutate(sq_err = (as.numeric(group.actual) - as.numeric(group.pred))^2) %>%
    summarize(RMSEP = sqrt(mean(sq_err))) %>%
    as.numeric()
}

pca_da <- function(data, X_vars, Y_var, CV = 7){
  X <- enquo(X_vars)
  Y <- enquo(Y_var)
  
  # Do PCA on X
  pca <- opls(select(data, !!X), plotL = FALSE, printL = FALSE)
  
  # Get scores and bind with Y
  scores <- get_scores(pca) %>% 
    add_column(!!Y := data[[quo_name(Y)]])
  
  # Make formula
  npcs <- pca@summaryDF$pre
  pcs <- glue("p{1:npcs}")
  mod_form <- as.formula(glue::glue("{quo_name(Y)} ~ {glue_collapse(pcs, sep = '+')}"))
  
  # Do regression
  m <- lda(mod_form, data = scores)
  
  # Do CV
  df.cv <- rsample::vfold_cv(data, CV)
  RMSEP <- df.cv %>%
    mutate(RMSEP = map_dbl(.$splits, ~pca_RMSEP_da(., !!X, !!Y))) %>% 
    summarize(RMSEP = mean(RMSEP)) %>%
    as.numeric()
  
  return(list(pca = pca, lm = m, RMSEP = RMSEP))
}



```



```{r}
library(holodeck)
```

```{r}
data <- df <-
  sim_cat(n_obs = 20, n_groups = 2) %>% 
  sim_covar(n_vars = 5, var = 1, cov = 0.3, name = "cov") %>% 
  group_by(group) %>% 
  sim_discr(n_vars = 5, var = 1, cov = 0.3, group_means = c(-1, 1), name = "d_1") %>% 
  sim_discr(n_vars = 5, var = 1, cov = 0.3, group_means = c(1.5, 0), name = "d_2") %>% 
  ungroup()
df
pcreg(df, -group, group) #.46
pca_lr(df, -group, group) #.19
pca_da(df, -group, group) #.12

<- lda(group ~ cov_1 + cov_2 + d_1_2 + d_1_1, data = df)
```


