---
title: "R Notebook"
output: html_notebook
---
# Libraries
```{r}
library(tidyverse)
library(here)
library(ropls)
```


Not taht interesting.  PCA and PLS show phenolics matter for decomposition

#Load data

```{r}
moss <- read_csv(here("data", "Rydin and Hajek", "bengtsson_etal_2018_LQ.csv"))
```

# Subset data

```{r}
moss_complete <- 
  moss %>%
  filter(!is.na(losslab2b), !is.na(lossfield))

moss_metab <- 
  moss_complete %>% 
  select(HC_mg_g, sphagn_litter_mg_g, phenolics_TA_mg_g, totalKL_mg_g, CEC_meq_g)
```

# PCA

```{r}
moss.pca <- opls(moss_metab, predI = 2)
plot(moss.pca, parAsColFcVn = moss_complete$losslab2b)
```


# PLSR to determine what metabolites contribute to decomp in lab and field

```{r}
# opls(moss_metab, moss_complete$lossfield) Fails, just like in paper.
opls_moss <- opls(moss_metab, moss_complete$losslab2b, predI = 1, orthoI = 1, permI = 500, plotL = FALSE)
plot_opls(opls_moss)
get_VIP(opls_moss) %>% arrange(desc(VIP)) 
```
Lignin most important.

Hows that compare to PCA?

```{r}
moss.pca %>% get_loadings() %>% arrange(desc(abs(p1)))
```
Almost the same

# Try kitchen sink??

```{r}
moss_all <-
  moss_complete %>% 
  select(HC_mg_g, sphagn_litter_mg_g, phenolics_TA_mg_g, KL_mg_g, CEC_meq_g, N_mg_g, C_mg_g, PO4_mg_g, solubleKL_mg_g, CNratio, HWT2012)
```

```{r}
pca_all <- opls(moss_all, plotL = FALSE)
plot(pca_all, parAsColFcVn = moss_complete$losslab2b)
```

```{r}
opls_all <- opls(moss_all, moss_complete$losslab2b, predI = 1, orthoI = 1,
                 # permI = 500,
                 plotL = FALSE)
plot_opls(opls_all)
get_VIP(opls_all) %>% arrange(desc(VIP))
```
```{r}
pca_all %>% 
  get_loadings() %>% 
  arrange(desc(abs(p1)))
```

about the same.