---
title: "PCA regression and PLS-DA models summary statistics"
output: html_notebook
---

- compare p-values and RMSEP from PCA regression and PLS-DA permutation tests
- Get other summary stats from PLS-DA models (e.g. R2, Q2)

- Make a table using gtable
  - columns = Scenario, statistic, PCA regression, PLS-DA
  -

```{r message=FALSE}
library(here)
library(tidyverse)
library(holodeck) #for get_* functions
# source(here("R","pcr.R"))
```

# Read in models

```{r}
control.pls <- read_rds(here('data', 'models', 'control-pls.rds'))
control.pcr <- read_rds(here('data', 'models', 'control-pcr.rds'))
null.pls <- read_rds(here('data', 'models', 'null-pls.rds'))
null.pcr <- read_rds(here('data', 'models', 'null-pcr.rds'))
needle.pls <- read_rds(here('data', 'models', 'needle-pls.rds'))
needle.pcr <- read_rds(here('data', 'models', 'needle-pcr.rds'))
```


# Get Summary Stats
## Map R2 and Q2 extractor

**Control**

```{r}
control.pls.summary <-
  control.pls %>%
  map(~get_modelinfo(.)) %>%
  map_dfr(~list(Q2_pls = pluck(., 2, "Q2(cum)"),
                R2Y_pls = pluck(., 2, "R2Y(cum)"),
                R2X_pls = pluck(., 2, "R2X(cum)"),
                pR2_pls = pluck(., 2, "pR2Y"),
                pQ2_pls = pluck(., 2, "pQ2"),
                RMSEP_pls = pluck(., 2, "RMSEE")),
          .id = "dataset") %>% 
  summarize_if(is.numeric, funs(mean, sd))

control.pcr.summary <- 
  control.pcr %>% 
  map_dfr(~broom::glance(.$lm), .id = "dataset") %>% 
  mutate(RMSEP = map_dbl(control.pcr, "RMSEP"),
         R2X = map_dbl(control.pcr, ~.$pca@summaryDF$`R2X(cum)`)) %>% 
  select(dataset, R2Y = r.squared, p = p.value, RMSEP, R2X) %>% 
  summarize_if(is.numeric, funs(mean, sd)) %>%
  gather() %>% 
  separate(key, into = c("Statistic", "part")) %>% 
  spread(key = part, value = value) %>% 
  mutate(value = glue("{round(mean, 3)} ± {round(sd, 3)}")) %>% 
  add_column(model = "PCA Regression")

control.pcr.summary
```



      
```{r} 
control.summary %>% 
  gather() %>% 
  separate(key, into = c("statistic", "model", "part")) %>% 
  spread(key = part, value = value) %>% 
  mutate(value = glue("{round(mean, 3)} ± {round(sd, 3)}")) %>% 
  select(-mean, -sd) %>% 
  spread(key = model, value = value)
```

**Null**

```{r}
null.pls %>%
  map(~get_modelinfo(.)) %>%
  map_dfr(~list(Q2 = pluck(., 2, "Q2(cum)"),
                R2 = pluck(., 2, "R2Y(cum)"),
                pR2 = pluck(., 2, "pR2Y"),
                pQ2 = pluck(., 2, "pQ2"),
                RMSEE = pluck(., 2, "RMSEE")),
          .id = "dataset") %>% 
  summarize_if(is.numeric, funs(mean, sd)) %>% 
    mutate(pcr_RMSEP = null.pcr %>% map_dbl("RMSEP") %>% mean(),
         pcr_RMSEP_sd = null.pcr %>% map_dbl("RMSEP") %>% sd())
```

**Needle-in-a-haystack**

```{r}
needle.pls %>%
  map(~get_modelinfo(.)) %>%
  map_dfr(~list(Q2 = pluck(., 2, "Q2(cum)"),
                R2 = pluck(., 2, "R2Y(cum)"),
                pQ2 = pluck(., 2, "pQ2"),
                RMSEE = pluck(., 2, "RMSEE")),
          .id = "dataset") %>% 
  summarize_if(is.numeric, funs(mean, sd)) %>% 
    mutate(pcr_RMSEP = needle.pcr %>% map_dbl("RMSEP") %>% mean(),
         pcr_RMSEP_sd = needle.pcr %>% map_dbl("RMSEP") %>% sd())
```

**Red Herring**

```{r}
# herring.pls %>%
#   map(~get_modelinfo(.)) %>%
#   map_dfr(~list(Q2 = pluck(., 2, "Q2(cum)"),
#                 R2 = pluck(., 2, "R2Y(cum)"),
#                 pQ2 = pluck(., 2, "pQ2")),
#           .id = "dataset") %>% 
#   summarize_if(is.numeric, funs(mean, sd))
```

