---
title: "PCA regression and PLS-DA models summary statistics"
output: html_notebook
---

```{r message=FALSE}
library(here)
library(tidyverse)
library(glue)

source(here("R", "ropls_helpers.R"))
source(here("R", "RMSEP.R"))
# runif(1, 0, 1000)
set.seed(464)
```

# Read in models

```{r}
control.pls <- read_rds(here('data', 'models', 'control-pls.rds'))
control.pls.forced <- read_rds(here('data', 'models', 'control-pls-force.rds'))
control.pcr <- read_rds(here('data', 'models', 'control-pcr.rds'))
null.pls <- read_rds(here('data', 'models', 'null-pls.rds'))
null.pls.forced <- read_rds(here('data', 'models', 'null-pls-force.rds'))
null.pcr <- read_rds(here('data', 'models', 'null-pcr.rds'))
needle.pls <- read_rds(here('data', 'models', 'needle-pls.rds'))
needle.pls.forced <- read_rds(here('data', 'models', 'needle-pls-force.rds'))
needle.pcr <- read_rds(here('data', 'models', 'needle-pcr.rds'))
```


# Get Summary Stats
## Function for getting summary stats

This is annoying because of the data structure.  I'm sure there is a more efficient way to do all this.

```{r}
# pls.forced <- null.pls.forced
# pls <- null.pls
# pcr <- null.pcr
# 
# pcr.test <- control.pcr[[1]]
# scores <- pcr.test$pca@scoreMN %>% as.data.frame()
```
```{r}
pls_pcr_summary <- function(pls, pls.forced, pcr) {
  pls.summary <-
    pls %>%
    # do RMSEP on successful models and store in summaryDF 
    map(~.x@summaryDF %>%
          mutate(RMSEP = plsda_RMSEP(.x, X_vars = -group, Y_var = group, CV = 7))) %>% 
    bind_rows(.id = "dataset") %>% 
    select(dataset, Q2 = `Q2(cum)`, R2Y = `R2Y(cum)`, R2X = `R2X(cum)`, pR2 = pR2Y, pQ2 = pQ2, RMSEP, ncomp = pre) %>% 
    summarize_if(is.numeric, funs(mean, sd)) %>% 
    gather() %>% 
    separate(key, into = c("Statistic", "part")) %>% 
    spread(key = part, value = value) %>% 
    mutate(`PLS-DA` = glue("{round(mean, 3)} ± {round(sd, 3)}")) %>% 
    select(-sd, -mean) %>% 
    add_row(Statistic = "n", `PLS-DA` = length(pls))
  
  pls.forced.summary <-
    pls.forced %>% 
    # do RMSEP on successful models and store in summaryDF 
    map(~.x@summaryDF %>%
          mutate(RMSEP = plsda_RMSEP(.x, X_vars = -group, Y_var = group, CV = 7))) %>% 
    bind_rows(.id = "dataset") %>% 
    select(dataset, Q2 = `Q2(cum)`, R2Y = `R2Y(cum)`, R2X = `R2X(cum)`, pR2 = pR2Y, pQ2 = pQ2, RMSEP, ncomp = pre) %>% 
    summarize_if(is.numeric, funs(mean, sd)) %>% 
    gather() %>% 
    separate(key, into = c("Statistic", "part")) %>% 
    spread(key = part, value = value) %>% 
    mutate("PLS-DA (ncomp forced)" = glue("{round(mean, 3)} ± {round(sd, 3)}")) %>% 
    select(-sd, -mean) %>% 
    add_row(Statistic = "n", "PLS-DA (ncomp forced)" = length(pls.forced))
  
  pcr.summary <- 
    pcr %>% 
    map_dfr(~.$mod.stats, .id = "dataset") %>% 
    mutate(RMSEP = map_dbl(pcr, "RMSEP"),
           R2X = map_dbl(pcr, ~.$pca@summaryDF$`R2X(cum)`),
           ncomp = map_dbl(pcr, ~.$pca@summaryDF$pre)) %>% 
    select(dataset, R2Y, p = p.value, RMSEP, R2X, ncomp) %>% 
    summarize_if(is.numeric, funs(mean, sd)) %>%
    gather() %>% 
    separate(key, into = c("Statistic", "part")) %>% 
    spread(key = part, value = value) %>% 
    mutate(`PCA-DA` = glue("{round(mean, 3)} ± {round(sd, 3)}")) %>% 
    select(-mean, -sd) %>% 
    add_row(Statistic = "n", `PCA-DA` = length(pcr))
  return(full_join(pls.summary, pls.forced.summary) %>% full_join(pcr.summary))
}
```

## Make table and write to .csv

```{r}
table1 <-
  list(control = pls_pcr_summary(control.pls, control.pls.forced, control.pcr),
       null = pls_pcr_summary(null.pls, null.pls.forced, null.pcr),
       needle = pls_pcr_summary(needle.pls, needle.pls.forced, needle.pcr)
  ) %>%
  bind_rows(.id = "Scenario")
table1 <- table1 %>% 
  mutate(Scenario = fct_relevel(Scenario, "null", "control", "needle"),
         Statistic = fct_relevel(Statistic,
                                 "n", "ncomp", "RMSEP", "R2X", "R2Y", "Q2", "pR2", "pQ2", "p")) %>% 
  arrange(Scenario, Statistic)
write_excel_csv(table1, here("figs", "table1.csv"))
```

## What % of p.values significant?

```{r}
needle_pcr_stats<- map_df(needle.pcr, 'mod.stats')
needle_pcr_stats %>% 
  summarize_all(mean)

needle_pcr_stats %>% 
  count(p.value < 0.05)

76/(76+21)

control_pcr_stats <- map_df(control.pcr, 'mod.stats')
control_pcr_stats %>% 
  summarize_all(mean)

control_pcr_stats %>% 
  count(p.value < 0.05)

#100%
```


