---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
 weeds <- 
  tibble(weed_taxum = 
           c("Amaranthus blitoides S. Watson",
             "Amaranthus retroflexus L.",
             "Arabidopsis thaliana (L.) Heynh.",
             "Artemisia frigida Willd.",
             "Avena fatua L.*",
             "Bassia scoparia (L.) A.J. Scott",
             "Brassicaceae sp.",
             "Bromus arvensis L.*",
             "Bromus tectorum L.*",
             "Buglossoides arvensis (L.) I.M. Johnst.",
             "Carthamus tinctorius L.",
             "Chenopodium album L.",
             "Chenopodium murale L.",
             "Cirsium arvense (L.) Scop.",
             "Descurainia pinnata (Walter) Britton",
             "Descurainia sophia (L.) Webb ex Prantl",
             "Fabaceae sp.",
             "Fagopyrum esculentum Moench",
             "Helianthus annuus L.",
             "Hordeum jubatum L.*",
             "Lactuca serriola L.",
             "Lens culinaris Medik.",
             "Leptochloa fusca (L.) Kunth *",
             "Medicago lupulina L.",
             "Medicago sativa L.",
             "Melilotus officinalis (L.) Lam.",
             "Monolepis nuttalliana (Schult.) Gree",
             "Pisum sativum L.",
             "Poa annua L.*",
             "Polygonum aviculare L.",
             "Polygonum convolvulus L.",
             "Pseudoroegneria spicata (Pursh)*",
             "Salsola kali L.",
             "Salvia reflexa Hornem.",
             "Setaria viridis (L.) P. Beauv. *",
             "Silene latifolia Poir.",
             "Sinapis arvensis L.",
             "Sisymbrium altissimum L.",
             "Solanum triflorum Nutt.",
             "Taraxacum officinale F.H. Wigg.",
             "Thlaspi arvense L.",
             "Tragopogon dubius Scop.",
             "Trifolium sp.",
             "Triticum aestivum L. *",
             "Unknown (dicot) sp.",
             "Unknown (grass) sp.*",
             "Vaccaria hispanica (Mill.) Rauschert",
             "Vicia americana Muhl. ex Willd."
           ),
         conventional = 
           c("<0.01",
             "<0.01",
             "-",
             "-",
             "4.71",
             "0.07",
             "-",
             "0.08",
             "8.40",
             "-",
             "-",
             "-",
             "-",
             "2.55",
             "<0.01",
             "-",
             "-",
             "-",
             "<0.01",
             "5.03",
             "0.12",
             "-",
             "<0.01",
             "-",
             "0.89",
             "-",
             "-",
             "-",
             "<0.01",
             "0.01",
             "0.13",
             "0.81",
             "2.72",
             "0.10",
             "0.13",
             "-",
             "-",
             "-",
             "-",
             "0.34",
             "-",
             "<0.01",
             "-",
             "-",
             "<0.01",
             "<0.01",
             "-",
             "<0.01"),
         organic = 
           c("<0.01",
             "0.47",
             "<0.01",
             "<0.01",
             "4.70",
             "0.14",
             "0.04",
             "<0.01",
             "0.20",
             "<0.01",
             "0.69",
             "7.43",
             "<0.01",
             "<0.01",
             "0.03",
             "0.01",
             "<0.01",
             "0.03",
             "2.72",
             "0.04",
             "0.43",
             "0.15",
             "-",
             "0.01",
             "3.50",
             "0.07",
             "<0.01",
             "1.08",
             "-",
             "0.14",
             "6.70",
             "-",
             "36.15",
             "0.01",
             "0.05",
             "<0.01",
             "2.23",
             "0.04",
             "<0.01",
             "0.04",
             "1.31",
             "-",
             "<0.01",
             "3.50",
             "0.81",
             "0.03",
             "0.63",
             "0.43")
  )

weeds
```

```{r}
weeds %>% 
  gather(-weed_taxum, key = farming, value = percent_composition) %>% 
  na_if("-") %>% 
  #convert to numeric somehow
  mutate(percent_composition =
           ifelse(percent_composition == "<0.01", 0.01, percent_composition) %>%
           as.numeric()) %>% 
  spread(key = weed_taxum, value = percent_composition)
```
Oh, shoot.  This is summary data, not the original data which included multiple farms of each type across three years.
